import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { eventServices } from '../../api/eventServices'
import SuccessModal from '../../components/common/SuccessModal'
import LoadingSpinner from '../../components/common/LoadingSpinner'

export default function CrearEventPage() {
  const navigate = useNavigate(); const [form, setForm] = useState({ name: '', event_type: '', date_event: '', location: '', client: '', description: '', user_id: '00000000-0000-0000-0000-000000000001' }); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [created, setCreated] = useState(null)
  const update = (name, value) => setForm((current) => ({ ...current, [name]: value }))
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { setCreated(await eventServices.createEvent(form)) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  return <div className="page narrow-page"><header className="page-header"><div><h1>Crear evento</h1><p>Construye el plan logístico inicial de tu evento.</p></div></header><form className="conversation-form" onSubmit={submit}><div className="form-block"><h2>¿Qué evento estás organizando?</h2><label className="form-field"><span>Nombre del evento*</span><input required value={form.name} placeholder="Ej. Boda de Luis y Alejandra" onChange={(e) => update('name', e.target.value)} /></label><label className="form-field"><span>Tipo de evento</span><input value={form.event_type} placeholder="Ej. Boda" onChange={(e) => update('event_type', e.target.value)} /></label></div><div className="form-block"><h2>¿Cuándo y dónde será?</h2><label className="form-field"><span>Fecha del evento*</span><input required type="date" value={form.date_event} onChange={(e) => update('date_event', e.target.value)} /></label><label className="form-field"><span>Lugar</span><input value={form.location} placeholder="Ej. Club Campestre Cali" onChange={(e) => update('location', e.target.value)} /></label></div><div className="form-block"><h2>¿Para quién es y qué debemos recordar?</h2><label className="form-field"><span>Cliente</span><input value={form.client} onChange={(e) => update('client', e.target.value)} /></label><label className="form-field"><span>Descripción</span><textarea value={form.description} onChange={(e) => update('description', e.target.value)} /></label></div>{error && <div className="server-error">{error}</div>}<button className="button button-primary submit-button" disabled={loading}>{loading ? <LoadingSpinner /> : 'Crear evento'}</button></form>{created && <SuccessModal title="¡Evento creado!" message="El evento ha sido creado con éxito" onAccept={() => navigate(`/evento/${created.id}`)} />}</div>
}
